/**
 * Emit the Poseidon t=3 parameter set + depth-20 zero-hashes as a Rust source file
 * for the on-chain Merkle tree in contracts/umbra-pool. The contract, the circuits,
 * and the TS wallet then all hash with the SAME constants → roots agree across all
 * three. Also prints cross-impl oracle vectors for the Rust unit test.
 *
 * Run: tsx packages/crypto-bls/scripts/gen-rust-constants.ts
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { poseidon2 } from "../src/poseidon.js";
import { paramsForT } from "../src/poseidon-params.js";
import { toBytesBE } from "../src/field.js";

// Slice depth = 8 (256 leaves). Keeps shield's on-chain Poseidon insertion (8 hashes)
// + the ~40M Groth16 verify inside the 100M tx budget (FEASIBILITY_REVIEW.md §1). The
// production target is depth 20 with in-circuit insertion (K3) so the contract never hashes.
const DEPTH = 8;
const here = dirname(fileURLToPath(import.meta.url));
const outDir = join(here, "..", "..", "..", "contracts", "umbra-pool", "src");
mkdirSync(outDir, { recursive: true });

function bytesLit(x: bigint): string {
  const b = toBytesBE(x, 32);
  return "[" + Array.from(b).map((n) => `0x${n.toString(16).padStart(2, "0")}`).join(", ") + "]";
}

const p = paramsForT(3);

// Zero-subtree hashes: Z[0] = 0, Z[i] = Poseidon2(Z[i-1], Z[i-1]).
const zeros: bigint[] = [0n];
for (let i = 1; i <= DEPTH; i++) zeros.push(poseidon2(zeros[i - 1]!, zeros[i - 1]!));

const cLines = p.c.map((v) => `    ${bytesLit(v)},`).join("\n");
const mLines = p.m.flat().map((v) => `    ${bytesLit(v)},`).join("\n");
const zLines = zeros.map((v) => `    ${bytesLit(v)},`).join("\n");

const rust = `// AUTO-GENERATED by @umbra/crypto-bls gen-rust-constants.ts — do not edit by hand.
// Umbra Poseidon t=3 over BLS12-381 Fr (R_F=${p.rf}, R_P=${p.rp}); depth-${DEPTH} zero-hashes.
// Bytes are 32-byte big-endian Fr scalars, the layout soroban_sdk Fr::from_bytes expects.

pub const POSEIDON_RF: usize = ${p.rf};
pub const POSEIDON_RP: usize = ${p.rp};
pub const MERKLE_DEPTH: usize = ${DEPTH};

/// Round constants, flat, length t*(R_F+R_P) = ${p.c.length}.
pub const POSEIDON_C: [[u8; 32]; ${p.c.length}] = [
${cLines}
];

/// MDS matrix (3x3), row-major.
pub const POSEIDON_M: [[u8; 32]; 9] = [
${mLines}
];

/// Zero-subtree hashes Z[0..=DEPTH].
pub const ZERO_HASHES: [[u8; 32]; ${zeros.length}] = [
${zLines}
];
`;

writeFileSync(join(outDir, "poseidon_constants.rs"), rust);

// eslint-disable-next-line no-console
console.log("wrote contracts/umbra-pool/src/poseidon_constants.rs");
// eslint-disable-next-line no-console
console.log("ORACLE poseidon2(1,2) =", "0x" + poseidon2(1n, 2n).toString(16));
// eslint-disable-next-line no-console
console.log("ORACLE poseidon2(3,4) =", "0x" + poseidon2(3n, 4n).toString(16));
// eslint-disable-next-line no-console
console.log("ORACLE zero_root (Z[" + DEPTH + "]) =", "0x" + zeros[DEPTH]!.toString(16));
