/**
 * Generate the Umbra Poseidon parameter set and emit it in BOTH formats:
 *   - JSON  (consumed by TypeScript / wallet code and by the benchmark vectors)
 *   - Circom (consumed by the circuits — same numbers, so circom ≡ TS by construction)
 *
 * Run: `pnpm --filter @umbra/crypto-bls run gen:constants`
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { generateParams } from "../src/poseidon-params.js";
import { FR_ORDER } from "../src/field.js";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, "..", "..", "..");
const outDir = join(repoRoot, "circuits", "src", "poseidon");
mkdirSync(outDir, { recursive: true });

const WIDTHS = [2, 3, 5]; // 1-, 2-, and 4-input Poseidon (nullifier/merkle/commitment)

function circomArray(name: string, values: bigint[]): string {
  const lits = values.map((v) => `        ${v.toString()}`).join(",\n");
  return `function ${name}() {\n    var c[${values.length}] = [\n${lits}\n    ];\n    return c;\n}\n`;
}

function circomMatrix(name: string, m: bigint[][]): string {
  const t = m.length;
  const rows = m
    .map((row) => `        [${row.map((v) => v.toString()).join(", ")}]`)
    .join(",\n");
  return `function ${name}() {\n    var m[${t}][${t}] = [\n${rows}\n    ];\n    return m;\n}\n`;
}

for (const t of WIDTHS) {
  const p = generateParams(t);

  // JSON form (hex strings to avoid bigint JSON issues).
  const json = {
    field: "BLS12-381 Fr",
    modulus: "0x" + FR_ORDER.toString(16),
    t: p.t,
    rf: p.rf,
    rp: p.rp,
    bitLen: p.bitLen,
    c: p.c.map((v) => "0x" + v.toString(16)),
    m: p.m.map((row) => row.map((v) => "0x" + v.toString(16))),
  };
  writeFileSync(join(outDir, `poseidon_params_t${t}.json`), JSON.stringify(json, null, 2) + "\n");

  // Circom form.
  const circom =
    `// AUTO-GENERATED by @umbra/crypto-bls scripts/gen-constants.ts — do not edit by hand.\n` +
    `// Umbra Poseidon parameter set over BLS12-381 Fr (t=${t}, R_F=${p.rf}, R_P=${p.rp}).\n` +
    `pragma circom 2.1.6;\n\n` +
    circomArray(`POSEIDON_T${t}_C`, p.c) +
    `\n` +
    circomMatrix(`POSEIDON_T${t}_M`, p.m);
  writeFileSync(join(outDir, `poseidon_constants_t${t}.circom`), circom);

  // eslint-disable-next-line no-console
  console.log(`wrote poseidon params t=${t}: ${p.c.length} constants, ${t}x${t} MDS`);
}

// eslint-disable-next-line no-console
console.log(`\nConstants written to ${outDir}`);
